<?xml version="1.0" encoding="utf-8"?><Database Name="Essay" Class="EssayDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=PX4\SQLEXPRESS;Initial Catalog=Essay;Integrated Security=True" SettingsObjectName="Essay.Properties.Settings" SettingsPropertyName="EssayConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="[User]" Member="User" Type="System.String" DbType="VarChar(250) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="LinkAVT" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Certification" Member="Certifications">
    <Type Name="Certification">
      <Column Name="IDCertificate" Type="System.String" DbType="VarChar(250) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="SID" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="IssueDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ExpiryDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Grade" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Student_Certification" Member="Student" ThisKey="SID" OtherKey="ID" Type="Student" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="[User]" Member="User" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Pass" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="birthDay" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="isOnline" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LinkAVT" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Employee_HistoryEmployee" Member="HistoryEmployees" ThisKey="ID" OtherKey="ID" Type="HistoryEmployee" />
    </Type>
  </Table>
  <Table Name="dbo.HistoryEmployee" Member="HistoryEmployees">
    <Type Name="HistoryEmployee">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeLogin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Employee_HistoryEmployee" Member="Employee" ThisKey="ID" OtherKey="ID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HistoryManager" Member="HistoryManagers">
    <Type Name="HistoryManager">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeLogin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Manager_HistoryManager" Member="Manager" ThisKey="ID" OtherKey="ID" Type="Manager" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Manager" Member="Managers">
    <Type Name="Manager">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="[User]" Member="User" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Pass" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="birthDay" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="isOnline" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LinkAVT" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Manager_HistoryManager" Member="HistoryManagers" ThisKey="ID" OtherKey="ID" Type="HistoryManager" />
    </Type>
  </Table>
  <Table Name="dbo.Student" Member="Students">
    <Type Name="Student">
      <Column Name="ID" Type="System.String" DbType="VarChar(250) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Class" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="birthDay" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="isDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Student_Certification" Member="Certifications" ThisKey="ID" OtherKey="SID" Type="Certification" />
    </Type>
  </Table>
</Database>